name: churn_pipeline
version: "1.0"
config-version: 2

profile: churn_profile

model-paths: ["models"]

models:
  churn_pipeline:
    staging:
      materialized: view
    production:
      materialized: table